name: Build TIPA without Certificates

on:
  workflow_dispatch: # 仅手动触发
  push:
    branches: [main]

jobs:
  build-tipa:
    runs-on: macOS-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Free Provisioning Profile
      env:
        APPLE_ID: ${{ secrets.FREE_APPLE_ID }}  # 普通Apple ID邮箱
        APPLE_PASSWORD: ${{ secrets.FREE_APPLE_PASSWORD }}  # App专用密码
      run: |
        # 生成临时签名描述文件
        echo "import os" > create_profile.py
        echo "from pathlib import Path" >> create_profile.py
        echo "os.system('mkdir -p ~/Library/MobileDevice/Provisioning\\\\ Profiles')" >> create_profile.py
        echo "open(Path.home() / 'Library' / 'MobileDevice' / 'Provisioning Profiles' / 'free.mobileprovision', 'w').close()" >> create_profile.py
        python3 create_profile.py

    - name: Install Dependencies
      run: |
        # 安装Xcode命令行工具
        xcode-select --install || true
        
        # 安装CocoaPods
        brew install cocoapods
        
        # 安装iOS自动签名工具
        pip install fastlane

    - name: Automatic Signing
      env:
        BUNDLE_ID: "com.example.tempapp"  # 替换为你的Bundle ID
        APP_NAME: "YourAppName"           # 替换为你的App名称
      run: |
        # 使用Fastlane自动创建免费签名
        fastlane run create_app_online \
          username:"${{ secrets.FREE_APPLE_ID }}" \
          app_identifier:"$BUNDLE_ID" \
          skip_itc:true
        
        # 生成自动签名配置
        cat << EOF > automatic_signing.rb
        require 'xcodeproj'
        project = Xcodeproj::Project.open('$APP_NAME.xcodeproj')
        project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
            config.build_settings['DEVELOPMENT_TEAM'] = ''
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
          end
        end
        project.save
        EOF
        
        ruby automatic_signing.rb

    - name: Build Unsigned IPA
      env:
        SCHEME_NAME: "YourScheme"   # 替换为你的Scheme名称
        APP_NAME: "YourAppName"     # 替换为你的App名称
      run: |
        # 清理项目
        xcodebuild clean -project "$APP_NAME.xcodeproj" -scheme "$SCHEME_NAME"
        
        # 构建应用
        xcodebuild build \
          -project "$APP_NAME.xcodeproj" \
          -scheme "$SCHEME_NAME" \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        # 创建Payload目录
        mkdir -p Payload
        cp -r "build/Release-iphoneos/$APP_NAME.app" Payload/
        
        # 压缩成IPA
        zip -r unsigned.ipa Payload
        
        # 重命名为TIPA
        mv unsigned.ipa application.tipa

    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Unsigned-TIPA
        path: application.tipa
